- hosts: localhost
  tasks:
    - name: Run whoami without become
      command: whoami
      changed_when: false
      become: false
      register: whoami
    - name: Install libraries with homebrew
      homebrew:
        name:
          - tmux
          - mas # Mac App Store cli
          - ffmpeg
          - awscli
          - nvm
        state: present
    - name: Install applications with hombrew cask
      homebrew_cask:
        name:
          - iterm2
          - visual-studio-code
          - google-chrome
          - slack
          - notion
          - todoist
          - docker
          - bitwarden
          - spotify
          - discord
          - mongodb-compass
          - fork
        state: present
    - name: Apply git configuration
      git_config:
        name="{{ item.name }}"
        value="{{ item.value }}"
        scope=global
      with_items:
        - { name: "user.name", value: "coderspinoza"} # TODO: make this into an env var
        - { name: "user.email", value: "hara0115@gmail.com" } # TODO: make this into an env var
        - { name: "ui.color",   value: "True" }
    - name: Install collection community
      community.general.ansible_galaxy_install:
        type: collection
        name: community.general
    - name: Install applications on Map App Store
      community.general.mas:
        id="{{ item }}"
        state=present
      with_items: # You can search for ids using 'mas search ${APP_NAME}'
        - 869223134 # KakaoTalk
        - 405399194 # Kindle
        - 1444383602 # GoodNotes
        - 405843582 # Alfred
        - 411643860 # DaisyDisk
    - name: Upgrade all installed Mac App Store apps
      community.general.mas:
        upgrade_all: true
    # - name: "Starting docker service" # Not applicable to Mac
    #   service:
    #     name: "docker"
    #     state: started
    #     enabled: yes
    - name: Install oh-my-zsh
      block:
        - name: Install oh-my-zsh for user
          shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
          args:
            creates: "~/.oh-my-zsh"
        - name: Copy predefined .zshrc
          copy:
            src: configs/.zshrc
            dest: ~/.zshrc
    - name: Install Iterm themes
      block:
        - name: Ensure directory exists
          file:
            path: "{{ ansible_env.HOME }}/ItermThemes"
            state: directory
            owner: "{{ whoami.stdout }}"
        - name: Download Iterm2 Homebrew theme
          get_url:
            url: https://raw.githubusercontent.com/mbadolato/iTerm2-Color-Schemes/master/schemes/Homebrew.itermcolors
            dest: "{{ ansible_env.HOME }}/ItermThemes"
    - name: Set up nvm
      block:
        - name: Create .nvm
          file:
            path: "{{ ansible_env.HOME }}/.nvm"
            state: directory
            owner: "{{ whoami.stdout }}"
        - name: Add environment variable to .zprofile
          blockinfile:
            path: ~/.zprofile
            block: |
              export NVM_DIR="$HOME/.nvm"
              source $(brew --prefix nvm)/nvm.sh
            create: yes
            state: present
            marker: "# {mark} ANSIBLE MANAGED NVM ENV VAR"
        - name: Source .zprofile
          shell: source ~/.zprofile
          args:
            executable: /bin/zsh